### ISSUE TITLE
Confusion between crane apply and kubectl apply steps

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-runner#17]
**What date were you attending the hackathon?**

12/13

**What scenario were you running when you encountered the issue?**

001 stateless app migration

---

Some commentary from the hackathon, some folks are getting tripped up with the
fact that two of the tasks are called "apply". We need to be more specific about
"crane apply" and "kubectl apply" and the distinction between the two.

**Comment by djzager** [comment]
I believe this has been addressed by more clearly naming the tasks `crane-apply` and `kubectl-apply-(files|kustomize)`.
