### ISSUE TITLE
[BUG] Issues with the tasks I had to fox for e2e demo

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-runner#34]
* Needed to add --insecure-skip-tls-verify to the oc login in the kubeconfig gen task

* Needed to remove optional flags:
+ /crane transform --ignored-patches-dir= --flags-file= --optional-flags= --export-dir=/var/crane/export --transform-dir=/var/crane/transform
Error: invalid argument "" for "--optional-flags" flag:  must be formatted as key=value

* Needed to fix `--nameSuffix`, should be `--namesuffix`

* No `tree` in kustomize task, change to `find`

I think these are probably issues to fix in your `alpha` branch @djzager before we bring that in, just logging here.

**Comment by eriknelson** [comment]
Also needed these: https://github.com/konveyor/crane-ui-plugin/issues/28

**Comment by djzager** [comment]
All of these should be addressed with #35
