### ISSUE TITLE
[BUG] input to optional field in clustertaks "crane-transform" is invalid

### ISSUE THREAD

**Issue by JaydipGabani** [konveyor/crane-runner#40]
Getting error while "crane-transform" cluster task is getting executed in the pipeline run.

**What did you expect to happen?**
Expected to work transform without invalid input error

**What actually happened?**
Getting error saying input to optional flag is invalid

```
STEP-CRANE-TRANSFORM

+ crane transform --ignored-patches-dir= --flags-file= '--optional-flags=[]' --export-dir=/var/crane/export --transform-dir=/var/crane/transform
Error: invalid argument "[]" for "--optional-flags" flag: [] must be formatted as key=value
```

**Comment by djzager** [comment]
Fixed by https://github.com/konveyor/crane-runner/pull/49
