### ISSUE TITLE
Stop hard coding crane-runner in all tasks

### ISSUE THREAD

**Issue by jmontleon** [konveyor/crane-runner#58]
Related to https://github.com/konveyor/crane-operator/issues/60 and https://github.com/konveyor/crane-runner/issues/57

**Comment by djzager** [comment]
Just for reference, this is where (in crane-operator) the ClusterTask image is overridden
https://github.com/konveyor/crane-operator/blob/ebd6f4753da775dafdae8afae423e37b8eca123b/controllers/operatorconfig_controller.go#L394-L396

**Comment by djzager** [comment]
It also appears, I hadn't noticed this, you can specify the image via params.
https://github.com/tektoncd/catalog/blob/main/task/docker-build/0.1/docker-build.yaml#L71

**Comment by jmontleon** [comment]
Ya, I guess this isn't an issue afterall. I'll go ahead and close it.
